In [86]:
import pandas as pd
details=pd.read_csv(r'C:\Users\USER\Downloads\ecommerce_order_details.csv')
orders=pd.read_csv(r'C:\Users\USER\Downloads\ecommerce_orders.csv')

In [90]:
details.head()

,order_id,amount,profit,quantity,category,sub_category,payment_mode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [88]:
import re
details.columns = [re.sub(r'(?<!^)(?=[A-Z])', '_', col).lower() 
              for col in details.columns]

In [89]:
details=details.rename(columns={'order _i_d':'order_id','sub-_category':'sub_category'})
details.columns

Index(['order_id', 'amount', 'profit', 'quantity', 'category', 'sub_category',
       'payment_mode'],
      dtype='str')

In [81]:
orders.head()

,order_id,order _date,customer_name,state,city,month,month_name
0,B-26055,2018-03-10,Harivansh,Uttar Pradesh,Mathura,March,3
1,B-25993,2018-02-03,Madhav,Delhi,Delhi,February,2
2,B-25973,2018-01-24,Madan Mohan,Uttar Pradesh,Mathura,January,1
3,B-25923,2018-12-27,Gopal,Maharashtra,Mumbai,December,12
4,B-25757,2018-08-21,Vishakha,Madhya Pradesh,Indore,August,8

In [95]:
import re
orders.columns = [re.sub(r'(?<!^)(?=[A-Z])', '_', col).lower() 
              for col in orders.columns]

In [97]:
orders=orders.rename(columns={'order _i_d':'order_id','order _date':'order_date'})
orders.columns

Index(['order_id', 'order_date', 'customer_name', 'state', 'city'], dtype='str')

In [6]:
orders['Order Date']=pd.to_datetime(orders['Order Date'],dayfirst=True)
orders['month']=orders['Order Date'].dt.month_name()
orders['month_name']=orders['Order Date'].dt.month

In [25]:
df=pd.merge(details,orders,on='Order ID',how='inner')
print(df.head())
print(df.info())

  Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0  B-25681    1096     658         7  Electronics  Electronic Games
1  B-26055    5729      64        14    Furniture            Chairs
2  B-25955    2927     146         8    Furniture         Bookcases
3  B-26093    2847     712         8  Electronics          Printers
4  B-25602    2617    1151         4  Electronics            Phones

   PaymentMode Order Date CustomerName           State     City    month  \
0          COD 2018-06-04       Bhawna  Madhya Pradesh   Indore     June
1          EMI 2018-03-10    Harivansh   Uttar Pradesh  Mathura    March
2          EMI 2018-01-16        Shiva     Maharashtra     Pune  January
3  Credit Card 2018-03-27       Sarita     Maharashtra     Pune    March
4  Credit Card 2018-04-01       Vrinda     Maharashtra     Pune    April

   month_name
0           6
1           3
2           1
3           3
4           4
<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   str
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   str
 5   Sub-Category  1500 non-null   str
 6   PaymentMode   1500 non-null   str
 7   Order Date    1500 non-null   datetime64[us]
 8   CustomerName  1500 non-null   str
 9   State         1500 non-null   str
 10  City          1500 non-null   str
 11  month         1500 non-null   str
 12  month_name    1500 non-null   int32
dtypes: datetime64[us](1), int32(1), int64(3), str(8)
memory usage: 146.6 KB
None

In [11]:
df.describe(include='all')

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,month,month_name
count,1500,1500.000000,1500.00000,1500.000000,1500,1500,1500,1500,1500,1500,1500,1500,1500.000000
unique,500,NaN,NaN,NaN,3,17,5,NaN,336,19,25,12,NaN
top,B-25656,NaN,NaN,NaN,Clothing,Saree,COD,NaN,Abhishek,Madhya Pradesh,Indore,March,NaN
freq,12,NaN,NaN,NaN,949,211,684,NaN,21,314,248,205,NaN
mean,NaN,291.847333,24.64200,3.743333,NaN,NaN,NaN,2018-06-14 21:56:09.600000,NaN,NaN,NaN,NaN,5.988667
min,NaN,4.000000,-1981.00000,1.000000,NaN,NaN,NaN,2018-01-01 00:00:00,NaN,NaN,NaN,NaN,1.000000
25%,NaN,47.750000,-12.00000,2.000000,NaN,NaN,NaN,2018-03-08 18:00:00,NaN,NaN,NaN,NaN,3.000000
50%,NaN,122.000000,8.00000,3.000000,NaN,NaN,NaN,2018-05-28 00:00:00,NaN,NaN,NaN,NaN,5.000000
75%,NaN,326.250000,38.00000,5.000000,NaN,NaN,NaN,2018-10-01 00:00:00,NaN,NaN,NaN,NaN,10.000000
max,NaN,5729.000000,1864.00000,14.000000,NaN,NaN,NaN,2018-12-31 00:00:00,NaN,NaN,NaN,NaN,12.000000
std,NaN,461.924620,168.55881,2.184942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.685864

In [12]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
month           0
month_name      0
dtype: int64

In [27]:
import re
df.columns = [re.sub(r'(?<!^)(?=[A-Z])', '_', col).lower() 
              for col in df.columns]

In [28]:

df=df.rename(columns={'order _i_d':'order_id','sub-_category':'sub_category', 'order _date':'order_date'})
df.columns

Index(['order_id', 'amount', 'profit', 'quantity', 'category', 'sub_category',
       'payment_mode', 'order_date', 'customer_name', 'state', 'city', 'month',
       'month_name'],
      dtype='str')

In [63]:
total_revenue=df['amount'].sum()
total_profit=df['profit'].sum()
total_orders=df['order_id'].nunique()
avg_order_val=total_revenue/total_orders
profit_margin = (total_profit / total_revenue) * 100
print(f"total_revenue      : {total_revenue:.0f}")
print(f"total_profit       : {total_profit:.0f}")
print(f"total_orders       : {total_orders}")
print(f"avg_order_val      :{avg_order_val:.2f}")
print(f" Profit Margin     : {profit_margin:.2f}%")

total_revenue      : 437771
total_profit       : 36963
total_orders       : 500
avg_order_val      :875.54
 Profit Margin     : 8.44%
291.8473333333333

In [48]:
category_summary=df.groupby('category').agg(total_revenue=('amount','sum'),total_profit=('profit','sum'),total_orders=('order_id','count'),avg_quantity=('quantity','mean')).reset_index()
print("\n=== Category Summary ===")
print(category_summary)

=== Category Summary ===
      category  total_revenue  total_profit  total_orders  avg_quantity
0     Clothing         144323         13325           949      3.704953
1  Electronics         166267         13162           308      3.746753
2    Furniture         127181         10476           243      3.888889

In [51]:
state_revenue=df.groupby('state')['amount'].sum().sort_values(ascending=False)
print("\n===Top 5 States by Revenue===")
print(state_revenue.head(5))

===Top 5 States by Revenue===
state
Maharashtra       102498
Madhya Pradesh     87463
Uttar Pradesh      38362
Delhi              22957
Rajasthan          22334
Name: amount, dtype: int64

In [52]:
payment_counts=df['payment_mode'].value_counts()
print(payment_counts)

payment_mode
COD            684
UPI            331
Debit Card     202
Credit Card    163
EMI            120
Name: count, dtype: int64

In [54]:
loss_orders = df[df['profit'] < 0]
print(f"\n⚠️  Loss-making records: {len(loss_orders)} ({len(loss_orders)/len(df)*100:.1f}%)")

⚠️  Loss-making records: 529 (35.3%)

In [57]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\USER\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [98]:
from sqlalchemy import create_engine

#mysql connection
username="root"
password="farzana90"
host="localhost"
port="3306"
database="ecommerce_analytics"
engine=create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#write DataFrame to Mysql
orders.to_sql("orders", engine,
              if_exists="replace", index=False)
details.to_sql("order_details", engine,
               if_exists="replace", index=False)

1500